### ISSUE TITLE
process.exit is not a function in pdf-poppler

### ISSUE THREAD

**Issue by priyankaShirude** [ArtToledo/Convert-multiple-files#1]
I am working on **react typescript** application. I am trying to convert **docx** file to **pdf**. I have installed the library ( npm i convert-multiple-files ). It was successfully installed. And after starting the server using npm start I am getting an error as below
.
![image](https://user-images.githubusercontent.com/55987639/111916593-ad7dc280-8aa1-11eb-831a-958dc18584a8.png)

**Comment by ArtToledo** [comment]
Hello, can you send the part of the code in which you are calling the function, please? I'm waiting.

**Comment by priyankaShirude** [comment]
I have just written this line of code which is given in example. 

![image](https://user-images.githubusercontent.com/55987639/111917182-98566300-8aa4-11eb-9ca7-c346c7417c70.png)

**Comment by priyankaShirude** [comment]
Hey, Please send me a solution. If you are getting the same error.

**Comment by ArtToledo** [comment]
Sorry for the delay in returning, the generation of images through a PDF was causing some problems, mainly due to environments ... I decided to remove it while looking for other solutions to implement, I recommend you take a look at the canvas, it helped me a lot here on work as interim lib.
